name: release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to use for the release."
        required: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
      - name: setup git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: verify with Maven
        run: |
          ./mvnw --batch-mode verify
      - name: prepare release
        run: |
          ./mvnw --batch-mode -Darguments=-DskipTests release:prepare -DreleaseVersion=${{ inputs.releaseVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  do-release:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: v${{ inputs.releaseVersion }}
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: create source distribution
        run: |
          ./mvnw --batch-mode package -DskipTests
      - name: release with JReleaser
        run: |
          ./mvnw --batch-mode jreleaser:release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
