name: build and release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: build with Maven
        run: ./mvnw --batch-mode package
      - name: upload source distribution
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: source-distribution
          path: target/distribution/JsonWheel.java
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download source distribution
        id: download-source-distribution
        uses: actions/download-artifact@v3
        with:
          name: source-distribution
          path: JsonWheel.java
      - name: Release source file
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.download-source-distribution.outputs.download-path}}/JsonWheel.java